zeppelin:
  image: dylanmei/zeppelin:0.6.0-stable
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    MASTER: local[*]
    SPARK_SUBMIT_OPTIONS: --files /zeppelin/classes/SparkPythonClassesDevTalks.py
  ports:
    - 8080:8080
  volumes:
    - ./data:/zeppelin/datasets/yelp
    - ./notebooks:/zeppelin/notebook
    - ./classes:/zeppelin/classes
